# Generated by Django 3.0.4 on 2020-07-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='name',
            field=models.CharField(max_length=20, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='req',
            name='phone',
            field=models.IntegerField(max_length=15, verbose_name='телефон'),
        ),
    ]
