# Generated by Django 3.0.4 on 2020-07-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enjine', '0002_auto_20200710_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='req',
            options={'verbose_name': 'Заявка'},
        ),
    ]
